[build]
  command = "npm install -g mermaid.cli && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.0.2"
  JEKYLL_ENV = "production"
  # Prevents jekyll-github-metadata from failing when not running on GitHub Actions
  PAGES_REPO_NWO = "karthikv1392/karthikv1392.github.io"
